[["test.general.test_items.TestBase.test_item_name_group_conflict [Puzzle Piece] (group_name='Puzzle Piece', game_name='Jigsaw')"]]
__expected__ = "fail"
__version__ = ">=0.0.4"

[["test.general.test_items.TestBase.test_item_name_group_has_valid_item [Puzzle Pieces] (group_name='Puzzle Pieces', game_name='Jigsaw')"]]
__expected__ = "fail"
__version__ = ">=0.2.0,<0.3.0"
