[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_PizzaTower_Steph')"]]
__expected__ = "fail"
__version__ = ">=0.0.4"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_PizzaTower_Steph')"]]
__expected__ = "fail"
__version__ = ">=0.0.4"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PizzaTower_Steph', option='true_end')"]]
__expected__ = "error"
__version__ = ">=0.0.4"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PizzaTower_Steph', option='hundred_percent')"]]
__expected__ = "error"
__version__ = ">=0.0.4"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PizzaTower_Steph', option='hundred_one_percent')"]]
__expected__ = "error"
__version__ = ">=0.0.4"
