[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_PLA_Miro')"]]
__expected__ = "fail"
__version__ = ">=1.1.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_PLA_Miro')"]]
__expected__ = "fail"
__version__ = ">=1.1.1"
