[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_PokemonSnap_AliRobotnik')"]]
__expected__ = "fail"
__version__ = ">=1.3.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_PokemonSnap_AliRobotnik')"]]
__expected__ = "fail"
__version__ = ">=1.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PokemonSnap_AliRobotnik', option='Normal_Pic_Checks_enabled')"]]
__expected__ = "error"
__version__ = ">=1.3.1"

[["test.general.test_options.TestOptions.test_pickle_dumps (game='Manual_PokemonSnap_AliRobotnik', option='Wonderful_Pic_Checks_enabled')"]]
__expected__ = "error"
__version__ = ">=1.3.1"
