[["test.general.test_reachability.TestBase.test_default_all_state_can_reach_everything [Region should be reached] (region='Mission Complete', game='Metroid Zero Mission')"]]
__expected__ = "fail"
__version__ = ">=0.1.2"

[["test.general.test_reachability.TestBase.test_default_all_state_can_reach_everything [Region should be reached] (region='Mission Accomplished!', game='Metroid Zero Mission')"]]
__expected__ = "fail"
__version__ = ">=0.2.0"
